// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRaquets;

#nullable disable

namespace WebApiRaquets.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220224193025_Brands")]
    partial class Brands
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiRaquets.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Player")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaquetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaquetId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WebApiRaquets.Entities.Raquet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Raquets");
                });

            modelBuilder.Entity("WebApiRaquets.Entities.Brand", b =>
                {
                    b.HasOne("WebApiRaquets.Entities.Raquet", "Raquet")
                        .WithMany("brand")
                        .HasForeignKey("RaquetId");

                    b.Navigation("Raquet");
                });

            modelBuilder.Entity("WebApiRaquets.Entities.Raquet", b =>
                {
                    b.Navigation("brand");
                });
#pragma warning restore 612, 618
        }
    }
}
